stack=[]
stack.append(5)
stack.append(3)
stack.append(8)
stack.append(6)
stack.append(4)
stack.pop()
stack.append(1)
stack.pop()
print(stack)
print(stack[::-1])
print('stack pop',stack.pop())
print('stack pop',stack.pop())
print('stack pop',stack.pop())
print('stack pop',stack.pop())